server:
  port: 8090

spring:
  application:
    name: reactive-core

# https://stackoverflow.com/questions/59553647/how-to-run-flyway-migration-for-reactive-r2dbc-driver-on-sprintboot-stratup:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive_core

logging:
  level:
    com.gini: DEBUG



